#!/bin/bash -l
#SBATCH --ntasks-per-node=2          
#SBATCH --time=00:40:00             
#SBATCH --job-name=test             
#SBATCH --cpus-per-task=1           
#SBATCH --error=job.%J.err  
#SBATCH --output=job.%J.out
#SBATCH -c 2
#SBATCH -n 32

#export SLURM_CPU_BIND="cores"
export OMP_NUM_THREADS=2




mpiexec ./MPI_Test

